# Generated by Django 5.0.6 on 2024-06-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la Categoria')),
                ('NombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('idPlanta', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Id de Planta')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Planta')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de la Planta')),
                ('stock', models.IntegerField(verbose_name='Stock de Planta')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
