# Generated by Django 5.0.6 on 2024-06-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_planta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='idPlanta',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Planta'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio de la Planta'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock de Planta'),
        ),
    ]
