# Generated by Django 5.0.6 on 2024-06-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_planta_idplanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion'),
        ),
    ]
