# Generated by Django 5.0.6 on 2024-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_planta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
    ]
